### ISSUE TITLE
Ontology vocabularies in distilledESL do not match the specification in ESL planning document

### ISSUE THREAD

**Issue by rht** [EconomicSL/destilledESL#4]
The [spec](https://github.com/EconomicSL/EconomicSL.github.io/blob/master/documents/planning.pdf) describes the following entities:
1. `Actor`
2. `Balance Sheet`
3. `Goods`
4. `Promise`
5. `Market`
6. `Sentence`
7. `Action` (listed in Appendix A)

While in the current distilledESL, the abstract classes are:
1. `Agent`, `Trade` (I think it should be `Trader`)
2. `Ledger`, `Mailbox`, `ObligationsAndGoodsMailbox`, `Account`
3. `Message`, `GoodMessage` (rather than `Good` as an ontological object), `ObligationMessage`
4. `Obligation`
5. `Simulation`
6. `Contract`
7. `Action`

Which one is more current, and which one is outdated and should be updated?

**Comment by DavoudTaghawiNejad** [comment]
The document refers to core-ESL and is therefor obsolete.

**Comment by rht** [comment]
[rationale needed] Why? The document has a simpler set of ontologies, also mentions FIPA-ACL for design consideration. Where can I find the documentation for distilledESL? If this does not exist yet, I can help to write it up.

**Comment by rht** [comment]
cc @EconomicSL

**Comment by DavoudTaghawiNejad** [comment]
We have seen that in practice core-ESL was not user friendly. Everybody
worked around it, it made simulations more instead of less complicated. The
workarounds have been 'distilled' into distilledESL which was developed in
a agile way rather following a design document.That is the origin of
distilledESL's name.
