### ISSUE TITLE
Where is main class?

### ISSUE THREAD

**Issue by zouhx11** [EconomicSL/destilledESL#5]
I build jar using maven, but can't run it with IntelliJ IDEA, and I find there is no Main-Class in Manifest.mf. So How can I successfully run the app, thanks!

**Comment by zouhx11** [comment]
Also I don't know how to use those csv files, it seems like there isn't any api for them.

**Comment by davidrpugh** [comment]
@zouhx11 This repo is not being actively developed and needs to be archived.  I would take a look at other repos that are under active development.
